#!/usr/bin/env node

function atou(c) {
  return `\\u${c.charCodeAt(0).toString(16)}`;
}

var strs = process.argv.slice(2);
if (!strs.length) strs.push('😘');
for (var i = 0, len = strs.length; i < len; ++i) {
  strs[i] = strs[i].split('').reduce((s, i) => {
    s += atou(i);
    return s;
  }, '');
}
console.log(strs.join(' '));
