#!/usr/bin/env node

var strs = process.argv.slice(2);
for (var i = 0, len = strs.length; i < len; ++i) {
  strs[i] = strs[i].split('').reduce((s, i) => {
    s += `u${i.charCodeAt(0).toString(16)}`;
    return s;
  }, '');
}
console.log(strs.join(''));