#!/usr/bin/env node

function get_emoji(point) {
  var offset = point - 0x10000,
    lead = 0xd800 + (offset >> 10),
    trail = 0xdc00 + (offset & 0x3ff);
  return String.fromCharCode(lead, trail);
}

var strs = process.argv.slice(2);
for (var s of strs) {
  var num = parseInt(s, 16);
  var emoji = get_emoji(num);
  console.log(emoji);
}
// eg. node utoe 0x1f604